fix: gitleaks が install されてなかった時に落とすように

diff --git a/config/git/hooks/pre-commit b/config/git/hooks/pre-commit
--- a/config/git/hooks/pre-commit
+++ b/config/git/hooks/pre-commit
@@ -2,8 +2,8 @@
 set -euo pipefail
 
 if ! command -v gitleaks &>/dev/null; then
-  echo "gitleaks is not installed. Skipping secret check."
-  exit 0
+  echo "gitleaks is not installed. Cannot secret check."
+  exit 1
 fi
 
 gitleaks protect --staged --redact
